# Generated by Django 2.2 on 2019-04-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bxdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=15)),
                ('book_id', models.IntegerField(max_length=15)),
                ('rating', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='book_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ggb_id', models.IntegerField(max_length=20)),
                ('tag_id', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bx_info',
            fields=[
                ('book_id', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('gb_id', models.IntegerField(max_length=20)),
                ('work_id', models.IntegerField(max_length=20)),
                ('isbn', models.CharField(max_length=15)),
                ('book_author', models.CharField(max_length=255)),
                ('publication_year', models.PositiveIntegerField(max_length=10)),
                ('original_title', models.CharField(max_length=255)),
                ('book_title', models.CharField(max_length=255)),
                ('language_code', models.CharField(max_length=10)),
                ('average_rating', models.FloatField(max_length=10)),
                ('ratings_count', models.IntegerField(max_length=10)),
                ('image_url', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('tag_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_id', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=11)),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='adminInfo',
            new_name='admin_info',
        ),
    ]
