# Generated by Django 2.2 on 2019-04-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bxdb', '0002_auto_20190417_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_tags',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_ratings',
            name='book_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book_ratings',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book_ratings',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book_tags',
            name='ggb_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book_tags',
            name='tag_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bx_info',
            name='book_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bx_info',
            name='gb_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bx_info',
            name='publication_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bx_info',
            name='ratings_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bx_info',
            name='work_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
