# Generated by Django 2.2 on 2019-04-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bxdb', '0003_auto_20190418_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_tags',
            old_name='ggb_id',
            new_name='gb_id',
        ),
    ]
