# Generated by Django 2.2 on 2019-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bxdb', '0004_auto_20190418_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
