# Generated by Django 2.2 on 2019-04-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bxdb', '0005_user_info_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
